blank_issues_enabled: false
contact_links:
  - name: LACOSA PRD
    url: https://github.com/<YOUR_ORG_OR_USER>/<YOUR_REPO>/blob/main/LACOSA_PRD.md
    about: Read the product spec before filing a new issue.
